apiVersion: v1
kind: Secret
metadata:
  name: tensorlab-ghcr-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: tensorlab-ghcr-charts
  url: ghcr.io/tensorlabresearch/charts
  enableOCI: "true"
