apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kokoros-pages
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kokoros
  source:
    repoURL: https://tensorlabresearch.github.io/helm-kokoros
    chart: kokoros
    targetRevision: 0.1.4
    helm:
      values: |
        gpu:
          enabled: true
          count: 1
          resourceKey: nvidia.com/gpu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
